version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GIN_MODE=release
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite-db
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=db.sqlite3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
