basePath: /api/v1
definitions:
  main.Product:
    properties:
      name:
        type: string
      price:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple API example using SQLite and Swagger
  title: Simple API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Product'
            type: array
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Product'
      summary: Create a new product
      tags:
      - products
swagger: "2.0"
